version: '3'

services:
  server:
    build: server/
    command: python3 ./app.py
    environment:
      SERVER_PORT: 4242

    ports:
      - 5000:5000
    networks:
      app_net:
        ipv4_address: 172.16.238.10 

  client:
    build: client/
    command: python3 ./app.py
    environment: 
      SERVER_IP: 172.16.238.10
      SERVER_PORT: 4242 

    ports:
      - 5001:5000
    networks:
      app_net:
        ipv4_address: 172.16.238.11

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24