version: '3.1'

services:
  server:
    build: 
      context: ./
      dockerfile: ./server/Dockerfile
    entrypoint:
      - python3
      - ./server/app.py
    environment:
      DB_ADDRESS: 172.16.238.12
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: example
      CLIENT_PORT: 80
    volumes:
      - ./server:/server
      - ./core:/core

    ports:
      - 5000:5000
    networks:
      app_net:
        ipv4_address: 172.16.238.10 

  client1:
    build: 
      context: ./
      dockerfile: ./client/Dockerfile
    entrypoint:
      - python3
      - ./client/app.py
    environment: 
      SERVER_IP: 172.16.238.10
      SERVER_PORT: 5000
    volumes:
      - ./client:/client
      - ./core:/core
    ports:
      - 5001:5000
    networks:
      app_net:
        ipv4_address: 172.16.238.11

  client2:
    build: 
      context: ./
      dockerfile: ./client/Dockerfile
    entrypoint:
      - python3
      - ./client/app.py
    environment: 
      SERVER_IP: 172.16.238.10
      SERVER_PORT: 5000
    volumes:
      - ./client:/client
      - ./core:/core
    ports:
      - 5002:5000
    networks:
      app_net:
        ipv4_address: 172.16.238.12


  client3:
    build: 
      context: ./
      dockerfile: ./client/Dockerfile
    entrypoint:
      - python3
      - ./client/app.py
    environment: 
      SERVER_IP: 172.16.238.10
      SERVER_PORT: 5000
    volumes:
      - ./client:/client
      - ./core:/core
    ports:
      - 5003:5000
    networks:
      app_net:
        ipv4_address: 172.16.238.13


        # Use postgres/example user/password credentials
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   networks:
  #     app_net:
  #       ipv4_address: 172.16.238.100

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     app_net:
  #       ipv4_address: 172.16.238.101

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24