version: '3.1'

services:
  server:
    build: 
      context: ./
      dockerfile: ./server/Dockerfile
    command: python3 ./server/app.py
    environment:
      DB_ADDRESS: 172.16.238.12
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: example
      CLIENT_PORT: 5001

    ports:
      - 5000:5000
    networks:
      app_net:
        ipv4_address: 172.16.238.10 

  client:
    build: 
      context: ./
      dockerfile: ./client/Dockerfile
    entrypoint:
      - python3
      - ./app/client/app.py
    environment: 
      SERVER_IP: 172.16.238.10
      SERVER_PORT: 5000
    volumes:
      - ./client:/app/client
      - ./core:/app/core
    ports:
      - 5001:5000
    networks:
      app_net:
        ipv4_address: 172.16.238.11

# Use postgres/example user/password credentials
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      app_net:
        ipv4_address: 172.16.238.12

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      app_net:
        ipv4_address: 172.16.238.13

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24